# Generated by Django 2.2.4 on 2019-08-31 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Yazar',
            new_name='Author',
        ),
    ]
